name: 'Setup Private Git Credentials'
description: 'Sets up global git config insteadOf URLs for private repository access, with automatic cleanup'
inputs:
  go-private:
    description: 'The GOPRIVATE environment variable'
    required: false
    default: ''
  gh-username:
    description: 'GitHub Username'
    required: false
    default: 'gh-netic-robot'
  gh-token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/cleanup/index.js'
