# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Go Continuous Integration

on:
  workflow_call:
    secrets:
      # gh_username and gh_password are needed if `go get` (driven by
      # `GOPRIVATE`) needs to clone private GitHub repositories using HTTPS,
      # and the default `GITHUB_TOKEN` doesn't have sufficient permissions.
      gh_username:
        required: false
      gh_token:
        required: false
      # satisfy actionlint
      GH_NETIC_ROBOT_CLASSIC_TOKEN:
        required: false
    inputs:
      go-version:
        description: "The version of Go to use"
        required: false
        type: string
      go-private:
        description: "The GOPRIVATE environment variable"
        required: false
        type: string
        default: github.com/containdk,github.com/neticdk
      run-benchmarks:
        description: "Run benchmarks"
        required: false
        default: false
        type: boolean
      run-release-test:
        description: "Run release dry-run using GoReleaser"
        required: false
        default: false
        type: boolean
      run-govulncheck:
        description: "Run govulncheck"
        required: false
        default: true
        type: boolean

jobs:
  tests:
    env:
      GOPRIVATE: "${{ inputs.go-private }}"
      GH_USERNAME: ${{ secrets.gh_username || 'gh-netic-robot' }}
      GH_TOKEN: ${{ secrets.gh_token || secrets.GH_NETIC_ROBOT_CLASSIC_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          # go-version takes precedence over go-version-file
          # if it is empty, go-version-file will be used
          go-version: ${{ inputs.go-version }}
          go-version-file: go.mod

      - name: Setup private repository access
        id: setup_git_creds
        if: inputs.go-private != ''
        run: git config --global url."https://${{ env.GH_USERNAME }}:${{ env.GH_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Install Go dependencies
        run: |
          go mod download
          go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: v2.1

      - name: Go Compile and Test
        run: go test -cover -v ./...

      - name: Run benchmarks
        if: inputs.run-benchmarks
        run: go test -bench=./... ./...

      - name: Install GoReleaser
        if: inputs.run-release-test
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: check

      - name: Clean up private repository access configuration
        if: always() && steps.setup_git_creds.outcome == 'success' && inputs.go-private != ''
        run: git config --global --unset url."https://${{ env.GH_USERNAME }}:${{ env.GH_TOKEN }}@github.com".insteadOf

  vuln-scan:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "${{ inputs.go-private }}"
      GH_USERNAME: ${{ secrets.gh_username || 'gh-netic-robot' }}
      GH_TOKEN: ${{ secrets.gh_token || secrets.GH_NETIC_ROBOT_CLASSIC_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          scan-type: "fs"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "library"

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          # go-version takes precedence over go-version-file
          # if it is empty, go-version-file will be used
          go-version: ${{ inputs.go-version }}
          go-version-file: go.mod

      - name: Setup private repository access
        id: setup_git_creds
        if: inputs.go-private != ''
        run: git config --global url."https://${{ env.GH_USERNAME }}:${{ env.GH_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Run govulncheck
        if: inputs.run-govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -format text ./...

      - name: Clean up private repository access configuration
        if: always() && steps.setup_git_creds.outcome == 'success' && inputs.go-private != ''
        run: git config --global --unset url."https://${{ env.GH_USERNAME }}:${{ env.GH_TOKEN }}@github.com".insteadOf
